import Foundation
import MacPilotRemoteProtocol

/// Persisted configuration for the iPhone local-network remote control.
///
/// The pairing *keys* never live here: only the device metadata is stored in
/// `config.json`, while every secret stays in the Keychain.
struct RemoteControlSettings: Codable, Equatable, Sendable {
    /// Remote control is off until the user opts in.
    var isEnabled: Bool = false
    /// Permanent MacPilot device identifier. Generated the first time the user
    /// enables remote control and kept forever so the iPhone recognises this Mac
    /// even when its name, IP or hostname changes.
    var deviceID: String?
    /// Name advertised over Bonjour. Defaults to the Mac's local host name.
    var deviceName: String?
    /// ISO-8601 timestamp of the first time remote control was enabled.
    var pairedDevices: [RemotePairedDevice] = []

    var resolvedDeviceID: UUID {
        if let deviceID, let uuid = UUID(uuidString: deviceID) { return uuid }
        return UUID()
    }

    var resolvedDeviceName: String {
        let trimmed = deviceName?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        if !trimmed.isEmpty { return trimmed }
        return Host.current().localizedName ?? "MacPilot"
    }
}

/// One iPhone that completed pairing.
struct RemotePairedDevice: Codable, Equatable, Identifiable, Sendable {
    /// Stable client identifier generated by the iPhone app.
    var id: String
    var name: String
    var createdAt: Date
    var lastConnectedAt: Date?
    /// Last host the device connected from, used only for display.
    var lastAddress: String?

    var displayName: String {
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? "iPhone" : trimmed
    }
}
