import AppKit
import Foundation
import Testing
@testable import MacPilot

/// 剪贴板采集决策与动作映射（纯逻辑）+ 历史导航/迁移/裁剪边界。
@MainActor
struct ClipboardCaptureTests {
    // MARK: - 采集过滤

    private var supportedTypes: Set<NSPasteboard.PasteboardType> {
        [.fileURL, .html, .png, .rtf, .string, .tiff, .jpeg, .heic]
    }

    @Test func unsupportedOrIgnoredTypeSetsAreSkipped() {
        #expect(ClipboardMonitor.shouldIgnoreTypes(
            [.autoGenerated, .string],
            supportedTypes: supportedTypes,
            ignoredTypes: [.autoGenerated, .concealed, .transient]
        ))
        #expect(ClipboardMonitor.shouldIgnoreTypes(
            [.transient],
            supportedTypes: supportedTypes,
            ignoredTypes: [.autoGenerated, .concealed, .transient]
        ))
        // 只有不受支持的类型（例如私有 UTI）。
        #expect(ClipboardMonitor.shouldIgnoreTypes(
            [NSPasteboard.PasteboardType("com.example.private")],
            supportedTypes: supportedTypes,
            ignoredTypes: [.autoGenerated, .concealed, .transient]
        ))
        // 正常文本复制不应被忽略。
        #expect(!ClipboardMonitor.shouldIgnoreTypes(
            [.string, .publicPlainTextFallbackType],
            supportedTypes: supportedTypes,
            ignoredTypes: [.autoGenerated, .concealed, .transient]
        ))
    }

    @Test func captureReadsStringContentFromPasteboardItem() throws {
        let item = NSPasteboardItem()
        item.setString("hello clipboard", forType: .string)

        let contents = ClipboardMonitor.captureContents(from: [item], itemID: UUID())

        #expect(contents.count == 1)
        #expect(contents.first?.type == NSPasteboard.PasteboardType.string.rawValue)
        #expect(String(data: try #require(contents.first?.value), encoding: .utf8) == "hello clipboard")
    }

    @Test func captureSkipsWhitespaceOnlyItemsWithoutRichText() throws {
        let empty = NSPasteboardItem()
        empty.setString("   \n", forType: .string)

        #expect(ClipboardMonitor.captureContents(from: [empty], itemID: UUID()).isEmpty)

        // 带富文本的空字符串不能跳过（富文本本身是有效内容）。
        let rich = NSPasteboardItem()
        rich.setString("   ", forType: .string)
        let rtf = NSAttributedString(string: "real").rtf(
            from: NSRange(location: 0, length: 4),
            documentAttributes: [:]
        )
        rich.setData(try #require(rtf), forType: .rtf)

        let contents = ClipboardMonitor.captureContents(from: [rich], itemID: UUID())
        #expect(contents.contains { $0.type == NSPasteboard.PasteboardType.rtf.rawValue })
    }

    @Test func captureFiltersDynamicAndMicrosoftSourcePrefixes() throws {
        let item = NSPasteboardItem()
        item.setString("visible", forType: .string)
        item.setData(Data([1]), forType: NSPasteboard.PasteboardType("dyn.aaa"))
        item.setData(Data([2]), forType: NSPasteboard.PasteboardType("com.microsoft.ole.source.x"))

        let contents = ClipboardMonitor.captureContents(from: [item], itemID: UUID())

        #expect(contents.map(\.type) == [NSPasteboard.PasteboardType.string.rawValue])
    }

    @Test func captureDropsMicrosoftBookmarkPairAndPdf() throws {
        let item = NSPasteboardItem()
        item.setString("doc text", forType: .string)
        item.setData(Data([1]), forType: .microsoftLinkSource)
        item.setData(Data([2]), forType: .microsoftObjectLink)
        item.setData(Data([3]), forType: .pdf)

        let contents = ClipboardMonitor.captureContents(from: [item], itemID: UUID())

        #expect(contents.map(\.type) == [NSPasteboard.PasteboardType.string.rawValue])
    }

    @Test func captureMergesMultiplePasteboardItemsInOrder() throws {
        // BBEdit/Edge 会写两个 item：应合并成一条记录，顺序保持。
        let first = NSPasteboardItem()
        first.setString("one", forType: .string)
        let second = NSPasteboardItem()
        second.setString("two", forType: .string)

        let contents = ClipboardMonitor.captureContents(from: [first, second], itemID: UUID())

        let values = contents.compactMap { $0.value.flatMap { String(data: $0, encoding: .utf8) } }
        #expect(values == ["one", "two"])
    }

    @Test func externalizationThresholdFollowsImageOrSizeRule() {
        let type = NSPasteboard.PasteboardType.string.rawValue
        let boundary = 64 * 1024

        #expect(!ClipboardContentStore.shouldExternalizeContent(type: type, dataSize: boundary))
        #expect(ClipboardContentStore.shouldExternalizeContent(type: type, dataSize: boundary + 1))
        #expect(ClipboardContentStore.shouldExternalizeContent(
            type: NSPasteboard.PasteboardType.png.rawValue,
            dataSize: 1
        ))
    }

    // MARK: - 动作映射

    @Test func modifierFlagsMapToActionsByPreference() {
        let command = NSEvent.ModifierFlags.command
        let option = NSEvent.ModifierFlags.option

        #expect(ClipboardAction(modifierFlags: command, pasteByDefault: true) == .paste)
        #expect(ClipboardAction(modifierFlags: command, pasteByDefault: false) == .copy)
        #expect(ClipboardAction(modifierFlags: option, pasteByDefault: true) == .copy)
        #expect(ClipboardAction(modifierFlags: option, pasteByDefault: false) == .paste)
        #expect(ClipboardAction(modifierFlags: [.option, .shift], pasteByDefault: true) == .pasteWithoutFormatting)
        #expect(ClipboardAction(modifierFlags: [.option, .shift], pasteByDefault: false) == .pasteWithoutFormatting)
        #expect(ClipboardAction(modifierFlags: [.command, .shift], pasteByDefault: true) == .pasteWithoutFormatting)
        #expect(ClipboardAction(modifierFlags: [.command, .shift], pasteByDefault: false) == .paste)
        #expect(ClipboardAction(modifierFlags: [], pasteByDefault: true) == .paste)
        #expect(ClipboardAction(modifierFlags: [], pasteByDefault: false) == .copy)
    }

    // MARK: - 导航

    private func makeItem(_ text: String, date: Date = Date()) -> ClipboardItem {
        var item = ClipboardItem(contents: [
            ClipboardContent(type: NSPasteboard.PasteboardType.string.rawValue, value: Data(text.utf8))
        ])
        item.title = text
        item.lastCopiedAt = date
        item.firstCopiedAt = date
        return item
    }

    private func makeHistoryWithContentIsolation() -> (ClipboardHistory, URL) {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("clipboard-content-\(UUID().uuidString)", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        ClipboardContentStore.directoryOverride = dir
        let history = ClipboardHistory(
            storageURL: FileManager.default.temporaryDirectory
                .appendingPathComponent("clipboard-\(UUID().uuidString).json")
        )
        return (history, dir)
    }

    @Test func navigationSelectsUnpinnedPinnedAndWraps() {
        let (history, contentDir) = makeHistoryWithContentIsolation()
        defer { ClipboardContentStore.directoryOverride = nil; try? FileManager.default.removeItem(at: contentDir) }

        history.add(makeItem("a", date: Date(timeIntervalSinceNow: -30)))
        history.add(makeItem("b", date: Date(timeIntervalSinceNow: -20)))
        history.add(makeItem("c", date: Date(timeIntervalSinceNow: -10)))
        // items 顺序：c, b, a
        #expect(history.items.map(\.title) == ["c", "b", "a"])

        history.selectFirst()
        #expect(history.selectedIndex == 0)
        history.moveSelectionDown()
        #expect(history.selectedIndex == 1)
        history.moveSelectionUp()
        #expect(history.selectedIndex == 0)
        history.moveSelectionUp()
        #expect(history.selectedIndex == 2)  // 环绕到末尾

        history.selectUnpinnedItem(at: 1)
        #expect(history.selectedItem?.title == "b")

        // 数字快捷键越界时不改变选择。
        history.selectUnpinnedItem(at: 9)
        #expect(history.selectedItem?.title == "b")
    }

    @Test func navigationSelectsPinnedItemByLetter() {
        let (history, contentDir) = makeHistoryWithContentIsolation()
        defer { ClipboardContentStore.directoryOverride = nil; try? FileManager.default.removeItem(at: contentDir) }

        var pinned = makeItem("pinned-item")
        pinned.pin = "b"
        history.add(pinned)
        history.add(makeItem("plain"))

        #expect(history.selectPinnedItem(withPin: "b"))
        #expect(history.selectedItem?.title == "pinned-item")
        #expect(!history.selectPinnedItem(withPin: "z"))
    }

    // MARK: - 迁移与裁剪边界

    @Test func legacyInlineImageMigratesToDiskOnLoad() throws {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("clipboard-content-\(UUID().uuidString)", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        ClipboardContentStore.directoryOverride = dir
        defer {
            ClipboardContentStore.directoryOverride = nil
            try? FileManager.default.removeItem(at: dir)
        }

        let pngData = Data(repeating: 0x7F, count: 2 * 1024)
        var legacyItem = ClipboardItem(contents: [
            ClipboardContent(
                type: NSPasteboard.PasteboardType.png.rawValue,
                value: pngData,
                size: pngData.count
            )
        ])
        legacyItem.title = "legacy"

        let jsonURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("clipboard-legacy-\(UUID().uuidString).json")
        defer { try? FileManager.default.removeItem(at: jsonURL) }
        try JSONEncoder().encode([legacyItem]).write(to: jsonURL, options: .atomic)

        let history = ClipboardHistory(storageURL: jsonURL)
        let content = try #require(history.allItems.first?.contents.first)

        #expect(content.value == nil)
        #expect(content.file != nil)
        #expect(content.file.flatMap(ClipboardContentStore.read(file:)) == pngData)
    }

    @Test func trimKeepsPinnedItemsBeyondTheConfiguredLimit() {
        let (history, contentDir) = makeHistoryWithContentIsolation()
        defer { ClipboardContentStore.directoryOverride = nil; try? FileManager.default.removeItem(at: contentDir) }

        history.storageLimit = 2

        var pinned = makeItem("pinned")
        pinned.pin = "a"
        history.add(pinned)
        history.add(makeItem("first"))
        history.add(makeItem("second"))

        // 固定条目可以超出 storageLimit；未固定条目保留最近复制的部分。
        #expect(history.allItems.count == 2)
        #expect(history.allItems.contains { $0.title == "pinned" })
        #expect(history.allItems.contains { $0.title == "second" })
        #expect(!history.allItems.contains { $0.title == "first" })
    }

    @Test func clearKeepsPinnedWhileClearAllRemovesEverything() {
        let (history, contentDir) = makeHistoryWithContentIsolation()
        defer { ClipboardContentStore.directoryOverride = nil; try? FileManager.default.removeItem(at: contentDir) }

        var pinned = makeItem("pinned")
        pinned.pin = "a"
        history.add(pinned)
        history.add(makeItem("plain"))

        history.clear()
        #expect(history.allItems.map(\.title) == ["pinned"])

        history.clearAll()
        #expect(history.allItems.isEmpty)
        #expect(history.items.isEmpty)
        #expect(history.searchQuery.isEmpty)
    }
}

extension NSPasteboard.PasteboardType {
    static let publicPlainTextFallbackType = NSPasteboard.PasteboardType(rawValue: "public.utf8-plain-text")
}
