import Foundation

/// Unified localization for the iOS app. Mirrors the Mac side's `AppText` so no
/// user visible string is hard coded in a view.
enum RemoteText {
    static func value(_ key: String, _ arguments: CVarArg...) -> String {
        let language = preferredLanguage
        let table = language == .simplifiedChinese ? chinese : english
        let format = table[key] ?? english[key] ?? key
        guard !arguments.isEmpty else { return format }
        return String(format: format, locale: language.locale, arguments: arguments)
    }

    enum Language {
        case english
        case simplifiedChinese

        var locale: Locale {
            switch self {
            case .english: return Locale(identifier: "en")
            case .simplifiedChinese: return Locale(identifier: "zh-Hans")
            }
        }
    }

    static var preferredLanguage: Language {
        let preferred = Locale.preferredLanguages.first ?? "en"
        return preferred.hasPrefix("zh") ? .simplifiedChinese : .english
    }

    private static let chinese: [String: String] = [
        "controlsSettings": "控制功能",
        "controlsSettingsHint": "选择要显示的控制功能，关闭后会隐藏对应控件。设置保存在本机，对所有 Mac 生效。",
        "controlsGroupInput": "触控与键盘",
        "controlsGroupScreen": "屏幕操作",
        "controlsGroupMedia": "媒体播放",
        "controlsGroupLevels": "亮度与音量",
        "controlsEmpty": "控制功能已全部隐藏，可前往设置重新开启。",
        "mediaPrevious": "上一曲",
        "mediaPlayPause": "播放 / 暂停",
        "mediaNext": "下一曲",
        "mediaNeedsUpdate": "请更新 Mac 上的 MacPilot 以使用媒体控制键。",
        "desktopTitle": "远程控制",
        "desktopHint": "Mac 实时画面、触控板与系统键盘",
        "desktopBluetooth": "当前为蓝牙连接，仅支持触控板。请连接 Wi-Fi 后重试。",
        "desktopNeedsUpdate": "请更新 MacPilot 以使用远程画面。",
        "desktopPermission": "请在 Mac 的系统设置中允许 MacPilot 录制屏幕，然后重试。",
        "desktopUnavailable": "远程画面暂不可用，触控板仍可使用。",
        "desktopDisplay": "选择显示器",
        "desktopDiagnostics": "视频诊断",
        "desktopOrientation": "方向",
        "desktopKeyboard": "键盘",
        "desktopFPS": "视频 %.1f FPS",
        "desktopEncode": "编码 %.1f ms",
        "desktopDecode": "解码 %.1f ms",
        "desktopNetwork": "网络 %.0f kb/s",
        "desktopDropped": "丢帧 %d",
        "desktopRTT": "控制 RTT %d ms",
        "appName": "PilotNest",
        "tabHome": "控制",
        "tabDevices": "设备",
        "tabSettings": "设置",
        "controllingMac": "当前控制的 Mac",
        "chooseMac": "选择 Mac",
        "switchMac": "切换",
        "switchMacAccessibility": "当前控制 %@，切换 Mac",
        "manageMacs": "管理设备",

        "stateIdle": "未连接",
        "stateDiscovering": "正在查找 Mac…",
        "stateConnecting": "正在连接…",
        "statePairing": "等待配对",
        "stateAuthenticating": "正在验证…",
        "stateConnected": "已连接",
        "stateReconnecting": "正在重新连接…",
        "stateFailed": "连接失败",
        "latency": "延迟 %d ms",
        "noMac": "未发现 MacPilot",
        "noMacDetail": "请确认 Mac 与 iPhone 在同一个 Wi-Fi，并且已在 MacPilot 的「远程控制」中启用 iPhone 遥控。",
        "retry": "重试",
        "openSystemSettings": "打开系统设置",
        "localNetworkHint": "需要允许「本地网络」权限才能发现 MacPilot。",
        "unrecognizedServiceHint": "发现了本地服务但读不到它的信息，可能对方版本不兼容。请把 MacPilot 更新到最新版。",
        "foundUnpaired": "发现 MacPilot",
        "foundUnpairedDetail": "已找到「%@」，去「设备」页点「配对」即可开始使用。",
        "goToPairing": "去配对",
        "noNewDevices": "本网络暂无可配对的新设备。",

        "actionLock": "锁屏",
        "actionDisplayOff": "黑屏",
        "actionWakeDisplay": "亮屏",
        "actionWakeAndUnlock": "唤醒解锁",
        "actionRunning": "执行中…",
        "actionDone": "完成",

        "levelsTitle": "亮度与音量",
        "brightnessLabel": "屏幕亮度",
        "volumeLabel": "音量",
        "mute": "静音",
        "unmute": "取消静音",
        "levelsUnavailable": "这台 Mac 暂不上报亮度或音量，请把 Mac 上的 MacPilot 更新到最新版。",
        "levelsUnavailableShort": "暂不可用",
        "levelsNotConnected": "连接后可在此调节 Mac 的亮度与音量。",

        "dockGroupsTitle": "Dock 小组",
        "dockGroupRefresh": "刷新小组",
        "dockGroupAppsRunning": "%d 个应用 · %d 个运行中",
        "dockGroupLaunch": "启动小组 %@",
        "dockGroupLaunchApp": "启动 %@",
        "dockGroupLaunchDone": "已在 Mac 上启动小组。",
        "dockGroupLaunchMissing": "未能启动：%@",
        "dockGroupsEmpty": "这台 Mac 还没有 Dock 小组。",
        "dockGroupsUnavailable": "暂时无法获取小组，点右上角刷新重试。",
        "dockGroupsNotConnected": "连接 Mac 后可以从这里一键打开小组。",
        "dockGroupExpandHint": "展开查看小组内的应用",
        "dockGroupEmptyHint": "这个小组还没有应用",

        "manualAdd": "通过 IP / 域名添加 Mac",
        "manualHost": "Mac 的 IP 地址或域名",
        "manualPort": "TCP 端口",
        "manualConnect": "连接",
        "manualInvalid": "请输入有效的 IP 或域名，以及 1–65535 的端口。",
        "manualHint": "支持局域网地址和 Tailscale IP / MagicDNS 域名。两端需开启 Tailscale 并允许连接。默认端口为 43847；若 Mac 使用其他端口，请填写实际端口。首次连接仍需输入 Mac 显示的配对码。",
        "desktopResetZoom": "还原画面缩放",
        "devicesTitle": "设备",
        "devicesSubtitle": "选择默认 Mac，或在局域网内发现新的 MacPilot。",
        "pairedSection": "已配对",
        "discoveredSection": "已发现",
        "searchDevices": "重新搜索设备",
        "pairDevice": "配对",
        "pairingConnecting": "正在连接设备，等待配对码…",
        "online": "在线",
        "offline": "离线",
        "connectedLabel": "已连接",
        "defaultMac": "默认",
        "setDefault": "设为默认",
        "forget": "移除",
        "forgetConfirmTitle": "移除这台 Mac？",
        "forgetConfirmMessage": "移除后会立即删除本机保存的配对密钥，之后需要重新配对。",
        "noPaired": "还没有已配对的 Mac。",

        "pairingTitle": "配对 MacPilot",
        "pairingSubtitle": "请在 Mac 上打开「设置 → 远程控制」，点击「开始配对」，然后输入 Mac 上显示的 6 位配对码。",
        "pairingCodePlaceholder": "6 位配对码",
        "pairingConfirm": "确认配对",
        "pairingCancel": "取消",
        "pairingWaiting": "正在等待 Mac 显示配对码…",
        "pairingSuccess": "配对成功",

        "settingsTitle": "设置",
        "settingsSubtitle": "本机标识、权限与连接偏好。",
        "clientName": "本机名称",
        "clientNameHint": "Mac 上会在已配对设备列表中看到这个名称。",
        "clientID": "本机标识",
        "permissions": "权限",
        "localNetwork": "本地网络",
        "granted": "已允许",
        "unknown": "未知",
        "resetPairings": "移除所有配对",
        "resetPairingsConfirm": "所有配对密钥都会从本机删除，需要重新配对。",
        "connectionPriority": "连接优先级",
        "connectionPriorityHint": "拖动调整顺序，越靠上优先级越高。三种方式仍同时连接，先连上的立即可用；更高优先级的方式连接成功后会自动切换。",
        "connectionMethodLocalNetwork": "局域网",
        "connectionMethodAwdl": "AWDL（点对点 Wi-Fi）",
        "connectionMethodBluetooth": "蓝牙",
        "transportSection": "连接方式",
        "transportCurrent": "当前链路",
        "transportRacing": "并发拨号",
        "transportRacingIdle": "未在拨号",
        "racePathBonjour": "Bonjour",
        "racePathRemembered": "地址直连",
        "racePathBluetooth": "蓝牙",
        "transportBLE": "蓝牙链路",
        "transportBLEOff": "未广播",
        "transportBLEAdvertising": "广播中",
        "transportBLEReady": "已就绪",
        "linkDiagnostics": "连接诊断记录",
        "linkShareDiagnostics": "导出连接诊断",
        "performance": "连接性能",
        "metricDiscovery": "发现耗时",
        "metricConnect": "连接耗时",
        "metricHandshake": "握手耗时",
        "metricRTT": "往返延迟",
        "metricExecution": "命令耗时",
        "about": "关于",
        "aboutBody": "PilotNest 通过局域网直连 Mac，不经过任何服务器。Mac 的登录密码始终保存在 Mac 上，不会传输到 iPhone。",

        "requirements": "使用前需要准备",
        "requirementsIntro": "PilotNest 只是手机上的遥控端，本身不能控制 Mac。请先在 Mac 上装好 MacPilot 并保持运行：",
        "requirementsStep1": "在 Mac 上安装 MacPilot（macOS 14 或更高版本）。",
        "requirementsStep2": "打开 MacPilot，在「远程控制」里启用 iPhone 遥控。",
        "requirementsStep3": "回到本 App，在「设备」页找到这台 Mac，点「配对」。",
        "requirementsStep4": "输入 Mac 上显示的 6 位配对码。之后会自动重连，不用再配对。",
        "requirementsDownload": "下载 MacPilot",
        "requirementsFooter": "两台设备需要在同一个 Wi-Fi 下，并允许「本地网络」权限。MacPilot 未运行或不在同一网络时，本 App 找不到 Mac。",

        "errorUnsupportedProtocol": "MacPilot 与 App 的协议版本不一致，请更新两端。",
        "errorPairingWindowClosed": "Mac 上没有打开配对窗口。请在 MacPilot 的「远程控制」中点击「开始配对」。",
        "errorInvalidPairCode": "配对码不正确，请重新输入。",
        "errorAuthenticationFailed": "配对验证失败，请重新配对。",
        "errorNotPaired": "这台 Mac 还没有与本机配对。",
        "errorNetwork": "网络连接中断，正在重试。",
        "errorUnauthenticated": "身份验证失败。",
        "errorPairingRequired": "需要先在 Mac 上完成配对。",
        "errorUnsupportedCommand": "Mac 不支持该操作，请更新 MacPilot。",
        "errorAccessibility": "请在 MacPilot 中授予「辅助功能」权限。",
        "errorCredential": "需要先在 MacPilot 中配置解锁密码。",
        "errorAlreadyLocked": "Mac 已经处于锁屏状态。",
        "errorAlreadyUnlocked": "Mac 已经解锁。",
        "errorUnlockFailed": "解锁失败，请确认 Mac 上的解锁密码正确。",
        "errorWakeFailed": "无法唤醒 Mac 的显示器。",
        "errorLockFailed": "锁屏未生效。",
        "errorDisplaySleepFailed": "关闭屏幕未生效。",
        "errorBrightnessUnavailable": "无法调节亮度：这台 Mac 没有可控制的屏幕背光（例如合盖外接显示器时）。",
        "errorVolumeUnavailable": "无法调节音量：Mac 上没有可调音量的输出设备。",
        "errorTimeout": "命令超时。",
        "errorInternal": "Mac 返回了内部错误。",

        "trackpadEntry": "触控板",
        "trackpadEntryHint": "把 iPhone 当作 Mac 的触控板",
        "trackpadTitle": "触控板",
        "trackpadNeedsMacUpdate": "需要把 Mac 端 MacPilot 更新到最新版。",
        "trackpadNotConnected": "未连接 Mac",
        "trackpadClose": "收起触控板",
        "trackpadReconnecting": "Mac 已断开，正在重新连接…",
        "trackpadDisconnected": "连接已断开",
        "trackpadBluetoothHint": "蓝牙连接延迟较高，触控板体验会打折扣。",
        "trackpadUseWiFi": "改用 Wi-Fi",
        "trackpadOrientation": "握持方向",
        "trackpadOrientationTop": "顶边朝上",
        "trackpadOrientationBottom": "底边朝上",
        "trackpadOrientationLeft": "左边朝上",
        "trackpadOrientationRight": "右边朝上",
        "trackpadSettings": "触控板设置",
        "trackpadTrackingSpeed": "跟踪速度",
        "trackpadNaturalScrolling": "自然滚动",
        "trackpadTapToClick": "轻点来点按",
        "trackpadScrollInertia": "滚动惯性",
        "trackpadDone": "完成",
        "trackpadHideKeyboard": "收起键盘",
        "trackpadShowKeyboard": "打开键盘",
        "trackpadGesturesHint": "单指移动光标；轻点＝左键，点在输入框上会打开键盘，连点两下＝双击；轻点两下后按住＝拖动；双指滑动＝滚动；双指轻点＝右键。触控板四边的箭头切换握持方向，点亮的箭头是当前朝向。",
        "trackpadPressure": "模拟按压",
        "trackpadPressureOff": "关闭",
        "trackpadPressureLight": "轻度",
        "trackpadPressureStandard": "标准",
        "trackpadPressureStrong": "增强",
        "trackpadPressureFooter": "通过触摸面积和按压持续时间模拟 Mac 触控板按压，压感应用（如画板）可读到按压力度。深度按压并保持＝按下，移动即拖动。",
        "trackpadPressureFeedback": "按压反馈",
        "trackpadPressureHintTitle": "模拟按压已开启",
        "trackpadPressureHintBody": "MacPilot 会根据手指接触面积和持续时间模拟触控板按压。不同手指和使用习惯可能需要调整灵敏度。",
        "trackpadDebugInfo": "调试信息",
        "trackpadDebugFooter": "在触控板页面上显示实时接触半径与按压判定。",
        "errorTextInputUnavailable": "Mac 上的输入框已失去焦点。",
    ]

    private static let english: [String: String] = [
        "controlsSettings": "Control features",
        "controlsSettingsHint": "Choose which controls to show. Turning a feature off hides its controls. Preferences are saved on this device and apply to all Macs.",
        "controlsGroupInput": "Trackpad & keyboard",
        "controlsGroupScreen": "Screen actions",
        "controlsGroupMedia": "Media playback",
        "controlsGroupLevels": "Brightness & volume",
        "controlsEmpty": "All controls are hidden. Enable them again in Settings.",
        "mediaPrevious": "Previous",
        "mediaPlayPause": "Play / Pause",
        "mediaNext": "Next",
        "mediaNeedsUpdate": "Update MacPilot on your Mac to use media controls.",
        "desktopTitle": "Remote control",
        "desktopHint": "Live Mac screen, trackpad and keyboard",
        "desktopBluetooth": "Bluetooth connection: trackpad only. Connect to Wi-Fi and retry.",
        "desktopNeedsUpdate": "Update MacPilot to use the remote screen.",
        "desktopPermission": "Allow MacPilot screen recording in Mac System Settings, then retry.",
        "desktopUnavailable": "Remote screen unavailable. The trackpad still works.",
        "desktopDisplay": "Choose display",
        "desktopDiagnostics": "Video diagnostics",
        "desktopOrientation": "Orientation",
        "desktopKeyboard": "Keyboard",
        "desktopFPS": "Video %.1f FPS",
        "desktopEncode": "Encode %.1f ms",
        "desktopDecode": "Decode %.1f ms",
        "desktopNetwork": "Network %.0f kb/s",
        "desktopDropped": "Dropped %d",
        "desktopRTT": "Control RTT %d ms",
        "appName": "PilotNest",
        "tabHome": "Control",
        "tabDevices": "Devices",
        "tabSettings": "Settings",
        "controllingMac": "Controlling Mac",
        "chooseMac": "Choose a Mac",
        "switchMac": "Switch",
        "switchMacAccessibility": "Controlling %@, switch Mac",
        "manageMacs": "Manage devices",

        "stateIdle": "Not connected",
        "stateDiscovering": "Looking for your Mac…",
        "stateConnecting": "Connecting…",
        "statePairing": "Waiting to pair",
        "stateAuthenticating": "Authenticating…",
        "stateConnected": "Connected",
        "stateReconnecting": "Reconnecting…",
        "stateFailed": "Connection failed",
        "latency": "%d ms",
        "noMac": "No MacPilot found",
        "noMacDetail": "Make sure the Mac and iPhone are on the same Wi-Fi and that iPhone remote control is enabled in MacPilot's Remote Control settings.",
        "retry": "Retry",
        "openSystemSettings": "Open Settings",
        "localNetworkHint": "Local Network access is required to find MacPilot.",
        "unrecognizedServiceHint": "Found a local service but could not read its details, which usually means a version mismatch. Update MacPilot on your Mac.",
        "foundUnpaired": "MacPilot found",
        "foundUnpairedDetail": "Found \"%@\". Open the Devices tab and tap Pair to get started.",
        "goToPairing": "Pair now",
        "noNewDevices": "No new devices to pair on this network.",

        "actionLock": "Lock",
        "actionDisplayOff": "Blank",
        "actionWakeDisplay": "Wake screen",
        "actionWakeAndUnlock": "Wake & Unlock",
        "actionRunning": "Working…",
        "actionDone": "Done",

        "levelsTitle": "Brightness & volume",
        "brightnessLabel": "Brightness",
        "volumeLabel": "Volume",
        "mute": "Mute",
        "unmute": "Unmute",
        "levelsUnavailable": "This Mac does not report brightness or volume yet. Update MacPilot on the Mac.",
        "levelsUnavailableShort": "Unavailable",
        "levelsNotConnected": "Connect to adjust your Mac's brightness and volume here.",

        "dockGroupsTitle": "Dock Groups",
        "dockGroupRefresh": "Refresh groups",
        "dockGroupAppsRunning": "%d apps · %d running",
        "dockGroupLaunch": "Launch group %@",
        "dockGroupLaunchApp": "Launch %@",
        "dockGroupLaunchDone": "Group launched on your Mac.",
        "dockGroupLaunchMissing": "Could not launch: %@",
        "dockGroupsEmpty": "This Mac has no Dock groups yet.",
        "dockGroupsUnavailable": "Couldn't load the groups. Tap refresh to try again.",
        "dockGroupsNotConnected": "Connect to a Mac to launch its Dock groups from here.",
        "dockGroupExpandHint": "Shows the apps in this group",
        "dockGroupEmptyHint": "This group has no apps yet",

        "manualAdd": "Add Mac by IP / hostname",
        "manualHost": "Mac IP address or hostname",
        "manualPort": "TCP port",
        "manualConnect": "Connect",
        "manualInvalid": "Enter a valid IP or hostname and a port from 1–65535.",
        "manualHint": "Use a LAN address or Tailscale IP / MagicDNS hostname. Enable Tailscale on both devices and allow connections. The default port is 43847; enter the actual port if your Mac uses another one. First connections still require the pairing code shown on the Mac.",
        "desktopResetZoom": "Reset preview zoom",
        "devicesTitle": "Devices",
        "devicesSubtitle": "Choose the default Mac or discover a new MacPilot on this network.",
        "pairedSection": "Paired",
        "discoveredSection": "Discovered",
        "searchDevices": "Search again",
        "pairDevice": "Pair",
        "pairingConnecting": "Connecting to device and waiting for pairing code…",
        "online": "Online",
        "offline": "Offline",
        "connectedLabel": "Connected",
        "defaultMac": "Default",
        "setDefault": "Set as default",
        "forget": "Remove",
        "forgetConfirmTitle": "Remove this Mac?",
        "forgetConfirmMessage": "The pairing key stored on this iPhone is deleted and you will need to pair again.",
        "noPaired": "No Mac has been paired yet.",

        "pairingTitle": "Pair with MacPilot",
        "pairingSubtitle": "On the Mac open Settings → Remote Control, click Start pairing, then type the 6 digit code shown on the Mac.",
        "pairingCodePlaceholder": "6 digit code",
        "pairingConfirm": "Pair",
        "pairingCancel": "Cancel",
        "pairingWaiting": "Waiting for the Mac to show a pairing code…",
        "pairingSuccess": "Paired",

        "settingsTitle": "Settings",
        "settingsSubtitle": "This iPhone's identity, permissions and connection preferences.",
        "clientName": "Device name",
        "clientNameHint": "The Mac shows this name in its paired device list.",
        "clientID": "Client ID",
        "permissions": "Permissions",
        "localNetwork": "Local Network",
        "granted": "Allowed",
        "unknown": "Unknown",
        "resetPairings": "Remove all pairings",
        "resetPairingsConfirm": "Every pairing key stored on this iPhone is deleted and you will need to pair again.",
        "connectionPriority": "Connection priority",
        "connectionPriorityHint": "Drag to reorder, highest priority first. All paths still connect in parallel. The first successful link is usable immediately; a higher-priority link takes over once connected.",
        "connectionMethodLocalNetwork": "Local network",
        "connectionMethodAwdl": "AWDL (peer-to-peer Wi-Fi)",
        "connectionMethodBluetooth": "Bluetooth",
        "transportSection": "Connection link",
        "transportCurrent": "Active link",
        "transportRacing": "Dialling",
        "transportRacingIdle": "Idle",
        "racePathBonjour": "Bonjour",
        "racePathRemembered": "Saved address",
        "racePathBluetooth": "Bluetooth",
        "transportBLE": "Bluetooth link",
        "transportBLEOff": "Not advertising",
        "transportBLEAdvertising": "Waiting for the Mac",
        "transportBLEReady": "Ready",
        "linkDiagnostics": "Connection diagnostics",
        "linkShareDiagnostics": "Export connection diagnostics",
        "performance": "Connection performance",
        "metricDiscovery": "Discovery",
        "metricConnect": "Connect",
        "metricHandshake": "Handshake",
        "metricRTT": "Round trip",
        "metricExecution": "Command",
        "about": "About",
        "aboutBody": "PilotNest talks to your Mac directly over the local network. Nothing goes through a server, and the Mac login password never leaves the Mac.",

        "requirements": "Before you start",
        "requirementsIntro": "PilotNest is only the remote control on your phone; it cannot control a Mac by itself. Install MacPilot on the Mac and keep it running:",
        "requirementsStep1": "Install MacPilot on the Mac (macOS 14 or later).",
        "requirementsStep2": "Open MacPilot and enable iPhone remote control under Remote Control.",
        "requirementsStep3": "Come back to this app, find the Mac on the Devices tab and tap Pair.",
        "requirementsStep4": "Type the 6 digit pairing code shown on the Mac. After that it reconnects on its own, with no re-pairing.",
        "requirementsDownload": "Download MacPilot",
        "requirementsFooter": "Both devices must be on the same Wi-Fi and allow Local Network access. If MacPilot is not running, or the Mac is on another network, this app cannot find it.",

        "errorUnsupportedProtocol": "This app and MacPilot speak different protocol versions. Update both.",
        "errorPairingWindowClosed": "The pairing window on the Mac is closed. Click Start pairing in MacPilot → Remote Control.",
        "errorInvalidPairCode": "That pairing code did not match. Try again.",
        "errorAuthenticationFailed": "Pairing verification failed. Please pair again.",
        "errorNotPaired": "This Mac has not been paired with this iPhone yet.",
        "errorNetwork": "The connection dropped. Reconnecting.",
        "errorUnauthenticated": "Authentication failed.",
        "errorPairingRequired": "Pair on the Mac first.",
        "errorUnsupportedCommand": "The Mac does not support that action. Update MacPilot.",
        "errorAccessibility": "Grant Accessibility permission in MacPilot on the Mac.",
        "errorCredential": "Set the unlock password in MacPilot on the Mac first.",
        "errorAlreadyLocked": "The Mac is already locked.",
        "errorAlreadyUnlocked": "The Mac is already unlocked.",
        "errorUnlockFailed": "Unlock failed. Check the unlock password saved on the Mac.",
        "errorWakeFailed": "Could not wake the Mac's display.",
        "errorLockFailed": "The Mac did not lock.",
        "errorDisplaySleepFailed": "The display did not turn off.",
        "errorBrightnessUnavailable": "Cannot change brightness: this Mac has no display with a controllable backlight (an external monitor in clamshell mode, for example).",
        "errorVolumeUnavailable": "Cannot change volume: no output device with a volume control.",
        "errorTimeout": "The command timed out.",
        "errorInternal": "The Mac reported an internal error.",

        "trackpadEntry": "Trackpad",
        "trackpadEntryHint": "Use your iPhone as a trackpad for your Mac",
        "trackpadTitle": "Trackpad",
        "trackpadNeedsMacUpdate": "Update MacPilot on your Mac to the latest version.",
        "trackpadNotConnected": "Mac not connected",
        "trackpadClose": "Close trackpad",
        "trackpadReconnecting": "Mac disconnected, reconnecting…",
        "trackpadDisconnected": "Connection lost",
        "trackpadBluetoothHint": "Bluetooth adds lag; the trackpad works best over Wi-Fi.",
        "trackpadUseWiFi": "Use Wi-Fi",
        "trackpadOrientation": "Orientation",
        "trackpadOrientationTop": "Top edge up",
        "trackpadOrientationBottom": "Bottom edge up",
        "trackpadOrientationLeft": "Left edge up",
        "trackpadOrientationRight": "Right edge up",
        "trackpadSettings": "Trackpad Settings",
        "trackpadTrackingSpeed": "Tracking speed",
        "trackpadNaturalScrolling": "Natural scrolling",
        "trackpadTapToClick": "Tap to click",
        "trackpadScrollInertia": "Scrolling inertia",
        "trackpadDone": "Done",
        "trackpadHideKeyboard": "Hide keyboard",
        "trackpadShowKeyboard": "Show keyboard",
        "trackpadGesturesHint": "One finger moves the cursor; tap = left click — tapping a text field opens the keyboard, double-tap = double click; double-tap and hold = drag; two-finger slide = scroll; two-finger tap = right click. The arrows on the trackpad edges switch the hold; the lit arrow is the current one.",
        "trackpadPressure": "Pressure Simulation",
        "trackpadPressureOff": "Off",
        "trackpadPressureLight": "Light",
        "trackpadPressureStandard": "Standard",
        "trackpadPressureStrong": "Strong",
        "trackpadPressureFooter": "Simulates Mac trackpad presses from touch area and hold duration; pressure-aware apps such as drawing surfaces read the grade. A deep press held still = button down; move to drag.",
        "trackpadPressureFeedback": "Press Feedback",
        "trackpadPressureHintTitle": "Pressure Simulation On",
        "trackpadPressureHintBody": "MacPilot now simulates trackpad presses from touch area and hold duration. Different fingers and habits may need a different mode.",
        "trackpadDebugInfo": "Debug Overlay",
        "trackpadDebugFooter": "Shows the live contact radius and press classification on the trackpad page.",
        "errorTextInputUnavailable": "The Mac text field lost focus.",
    ]
}

extension RemoteText {
    static func t(_ key: String, _ arguments: CVarArg...) -> String {
        value(key, arguments)
    }
}
