//
//  ClipboardMonitor.swift
//  MacPilot
//
//  剪贴板监听与复制/粘贴执行。
//  改编自 Maccy（MIT License, https://github.com/p0deje/Maccy）：
//  - Maccy/Clipboard.swift
//

import AppKit
import ApplicationServices
import Carbon.HIToolbox
import CoreGraphics
import OSLog

@MainActor
final class ClipboardMonitor {
    private static let logger = Logger(subsystem: "com.misswell.macpilot", category: "Clipboard")

    typealias OnNewCopyHook = (ClipboardItem) -> Void
    typealias SettingsProvider = () -> ClipboardSettings

    private var onNewCopyHooks: [OnNewCopyHook] = []
    private var changeCount: Int

    private let pasteboard = NSPasteboard.general
    private var timer: Timer?

    /// 打开面板期间暂停记录（避免粘贴自身被再次记录）。
    var isSuspended = false {
        didSet {
            if !isSuspended {
                // 恢复监听时先同步当前 changeCount，避免把面板期间的变化补录。
                changeCount = pasteboard.changeCount
            }
        }
    }

    /// 从 ClipboardModel 读取最新设置。
    var settingsProvider: SettingsProvider?

    private let dynamicTypePrefix = "dyn."
    private let microsoftSourcePrefix = "com.microsoft.ole.source."
    private let supportedTypes: Set<NSPasteboard.PasteboardType> = [
        .fileURL, .html, .png, .rtf, .string, .tiff, .jpeg, .heic
    ]
    private let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        .autoGenerated, .concealed, .transient
    ]

    init() {
        changeCount = pasteboard.changeCount
    }

    func onNewCopy(_ hook: @escaping OnNewCopyHook) {
        onNewCopyHooks.append(hook)
    }

    func start() {
        guard timer == nil else { return }
        timer = Timer.scheduledTimer(
            timeInterval: 0.5,
            target: self,
            selector: #selector(checkForChangesInPasteboard),
            userInfo: nil,
            repeats: true
        )
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// 从面板复制纯文本（把搜索词写入系统剪贴板）。
    func copy(_ string: String) {
        pasteboard.clearContents()
        pasteboard.setString(string, forType: .string)
        pasteboard.setString(NSPasteboard.PasteboardType.fromMaccy.rawValue, forType: .source)
        checkForChangesInPasteboard()
    }

    /// 把历史条目写回系统剪贴板。
    func copy(_ item: ClipboardItem, removeFormatting: Bool = false) {
        var contents = item.contents
        if removeFormatting {
            contents = clearFormatting(contents)
        }

        pasteboard.clearContents()

        for content in contents where content.type != NSPasteboard.PasteboardType.fileURL.rawValue {
            guard let value = item.resolvedData(for: content) else { continue }
            pasteboard.setData(value, forType: NSPasteboard.PasteboardType(content.type))
        }

        // 文件 URL 使用 writeObjects，让多文件复制真正生效。
        let fileURLItems: [NSPasteboardItem] = contents.compactMap { content in
            guard content.type == NSPasteboard.PasteboardType.fileURL.rawValue,
                  let value = item.resolvedData(for: content) else { return nil }
            let pasteItem = NSPasteboardItem()
            pasteItem.setData(value, forType: NSPasteboard.PasteboardType(content.type))
            return pasteItem
        }
        pasteboard.writeObjects(fileURLItems)

        pasteboard.setString("", forType: .fromMaccy)
        pasteboard.setString(item.application ?? "", forType: .source)

        checkForChangesInPasteboard()
    }

    /// 模拟按下 ⌘V 执行粘贴（需要辅助功能权限）。
    func paste() {
        let options = ["AXTrustedCheckOptionPrompt": true] as CFDictionary
        guard AXIsProcessTrustedWithOptions(options) else { return }

        let cmdFlag = CGEventFlags.maskCommand
        let vCode: CGKeyCode = UInt16(kVK_ANSI_V)

        let source = CGEventSource(stateID: .combinedSessionState)
        source?.setLocalEventsFilterDuringSuppressionState(
            [.permitLocalMouseEvents, .permitSystemDefinedEvents],
            state: .eventSuppressionStateSuppressionInterval
        )

        let keyDown = CGEvent(keyboardEventSource: source, virtualKey: vCode, keyDown: true)
        let keyUp = CGEvent(keyboardEventSource: source, virtualKey: vCode, keyDown: false)
        keyDown?.flags = cmdFlag
        keyUp?.flags = cmdFlag
        keyDown?.post(tap: .cgSessionEventTap)
        keyUp?.post(tap: .cgSessionEventTap)
    }

    func clearSystemClipboard() {
        pasteboard.clearContents()
    }

    @objc
    func checkForChangesInPasteboard() {
        guard !isSuspended else { return }
        guard pasteboard.changeCount != changeCount else { return }

        changeCount = pasteboard.changeCount

        // 面板自身复制产生的变化：只更新 changeCount，不记录。
        if pasteboard.pasteboardItems?.contains(where: { $0.types.contains(.fromMaccy) }) == true {
            return
        }

        // 读取类型时 NSPasteboard 会给出所有可用类型，甚至包括
        // NSPasteboardItem 上不存在的类型。
        guard !shouldIgnore(Set(pasteboard.types ?? [])) else { return }

        // 某些应用（BBEdit、Edge）复制时会写入 2 个 item，
        // 合并成一个记录。
        let itemID = UUID()
        var contents = [ClipboardContent]()
        pasteboard.pasteboardItems?.forEach { item in
            var types = Set(item.types)
            if types.contains(.string) && isEmptyString(item) && !richText(item) {
                return
            }

            types = types
                .filter { !$0.rawValue.starts(with: dynamicTypePrefix) }
                .filter { !$0.rawValue.starts(with: microsoftSourcePrefix) }

            // 避免读取 Microsoft Word 书签与交叉引用链接。
            if types.isSuperset(of: [.microsoftLinkSource, .microsoftObjectLink]) {
                types = types.subtracting([.microsoftLinkSource, .microsoftObjectLink, .pdf])
            }

            var index = 0
            types.forEach { type in
                let data = item.data(forType: type)
                contents.append(Self.makeContent(type: type.rawValue, data: data, itemID: itemID, index: &index))
            }
        }

        guard !contents.isEmpty else { return }

        var historyItem = ClipboardItem(id: itemID, contents: contents)
        historyItem.application = frontmostApplicationBundleIdentifier()
        historyItem.title = historyItem.generateTitle()

        onNewCopyHooks.forEach { $0(historyItem) }
    }

    /// 大数据（图片、大段内容）落盘保存，内存里只保留文件引用，减少常驻内存。
    private static func makeContent(
        type: String,
        data: Data?,
        itemID: UUID,
        index: inout Int
    ) -> ClipboardContent {
        defer { index += 1 }
        guard let data, !data.isEmpty else {
            return ClipboardContent(type: type, size: 0)
        }
        let externalize = ClipboardContentStore.shouldExternalizeContent(type: type, dataSize: data.count)
        if externalize, let file = ClipboardContentStore.write(data, itemID: itemID, index: index) {
            return ClipboardContent(type: type, file: file, size: data.count)
        }
        return ClipboardContent(type: type, value: data, size: data.count)
    }

    private func frontmostApplicationBundleIdentifier() -> String? {
        NSWorkspace.shared.frontmostApplication?.bundleIdentifier
    }

    private func shouldIgnore(_ types: Set<NSPasteboard.PasteboardType>) -> Bool {
        let ignored = ignoredTypes
        return types.isDisjoint(with: supportedTypes) || !types.isDisjoint(with: ignored)
    }

    private func isEmptyString(_ item: NSPasteboardItem) -> Bool {
        guard let string = item.string(forType: .string) else { return true }
        return string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    private func richText(_ item: NSPasteboardItem) -> Bool {
        if let rtf = item.data(forType: .rtf),
           let attributedString = NSAttributedString(rtf: rtf, documentAttributes: nil) {
            return !attributedString.string.isEmpty
        }
        if let html = item.data(forType: .html),
           let attributedString = NSAttributedString(html: html, documentAttributes: nil) {
            return !attributedString.string.isEmpty
        }
        return false
    }

    private func clearFormatting(_ contents: [ClipboardContent]) -> [ClipboardContent] {
        let stringContents = contents.filter { NSPasteboard.PasteboardType($0.type) == .string }
        guard !stringContents.isEmpty else { return contents }

        var newContents = stringContents
        let fileURLContents = contents.filter { NSPasteboard.PasteboardType($0.type) == .fileURL }
        if !fileURLContents.isEmpty {
            newContents += fileURLContents
        }
        return newContents
    }
}
