//
//  ClipboardMonitor.swift
//  MacPilot
//
//  剪贴板监听与复制/粘贴执行。采集过滤决策见底部的纯函数段（可单测）。
//

import AppKit
import ApplicationServices
import Carbon.HIToolbox
import CoreGraphics
import OSLog

@MainActor
final class ClipboardMonitor {
    private static let logger = Logger(subsystem: "com.misswell.macpilot", category: "Clipboard")

    typealias OnNewCopyHook = (ClipboardItem) -> Void
    typealias SettingsProvider = () -> ClipboardSettings

    private var onNewCopyHook: OnNewCopyHook?
    private var changeCount: Int

    private let pasteboard = NSPasteboard.general
    private var timer: Timer?

    /// 打开面板期间暂停记录（避免粘贴自身被再次记录）。
    var isSuspended = false {
        didSet {
            if !isSuspended {
                // 恢复监听时先同步当前 changeCount，避免把面板期间的变化补录。
                changeCount = pasteboard.changeCount
            }
        }
    }

    /// 从 ClipboardModel 读取最新设置。
    var settingsProvider: SettingsProvider?

    private let supportedTypes: Set<NSPasteboard.PasteboardType> = [
        .fileURL, .html, .png, .rtf, .string, .tiff, .jpeg, .heic
    ]
    private let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        .autoGenerated, .concealed, .transient
    ]

    init() {
        changeCount = pasteboard.changeCount
    }

    func onNewCopy(_ hook: @escaping OnNewCopyHook) {
        onNewCopyHook = hook
    }

    func start() {
        guard timer == nil else { return }
        let newTimer = Timer.scheduledTimer(
            timeInterval: Self.pollingInterval,
            target: self,
            selector: #selector(checkForChangesInPasteboard),
            userInfo: nil,
            repeats: true
        )
        // .common 让菜单跟踪、滚动条拖动等模态期间照常轮询
        // （仅 .default 模式时这些场景下轮询会暂停）。
        RunLoop.main.add(newTimer, forMode: .common)
        timer = newTimer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// 从面板复制纯文本（把搜索词写入系统剪贴板）。
    func copy(_ string: String) {
        pasteboard.clearContents()
        pasteboard.setString(string, forType: .string)
        pasteboard.setString("", forType: .fromMacPilot)
        pasteboard.setString(Bundle.main.bundleIdentifier ?? "", forType: .source)
        checkForChangesInPasteboard()
    }

    /// 把历史条目写回系统剪贴板。
    func copy(_ item: ClipboardItem, removeFormatting: Bool = false) {
        var contents = item.contents
        if removeFormatting {
            contents = clearFormatting(contents)
        }

        pasteboard.clearContents()

        for content in contents where content.type != NSPasteboard.PasteboardType.fileURL.rawValue {
            guard let value = item.resolvedData(for: content) else { continue }
            pasteboard.setData(value, forType: NSPasteboard.PasteboardType(content.type))
        }

        // 文件 URL 使用 writeObjects，让多文件复制真正生效。
        let fileURLItems: [NSPasteboardItem] = contents.compactMap { content in
            guard content.type == NSPasteboard.PasteboardType.fileURL.rawValue,
                  let value = item.resolvedData(for: content) else { return nil }
            let pasteItem = NSPasteboardItem()
            pasteItem.setData(value, forType: NSPasteboard.PasteboardType(content.type))
            return pasteItem
        }
        pasteboard.writeObjects(fileURLItems)

        pasteboard.setString("", forType: .fromMacPilot)
        pasteboard.setString(item.application ?? "", forType: .source)

        checkForChangesInPasteboard()
    }

    /// 模拟按下 ⌘V 执行粘贴（需要辅助功能权限）。
    func paste() {
        let options = ["AXTrustedCheckOptionPrompt": true] as CFDictionary
        guard AXIsProcessTrustedWithOptions(options) else { return }

        let cmdFlag = CGEventFlags.maskCommand
        let vCode: CGKeyCode = UInt16(kVK_ANSI_V)

        let source = CGEventSource(stateID: .combinedSessionState)
        source?.setLocalEventsFilterDuringSuppressionState(
            [.permitLocalMouseEvents, .permitSystemDefinedEvents],
            state: .eventSuppressionStateSuppressionInterval
        )

        let keyDown = CGEvent(keyboardEventSource: source, virtualKey: vCode, keyDown: true)
        let keyUp = CGEvent(keyboardEventSource: source, virtualKey: vCode, keyDown: false)
        keyDown?.flags = cmdFlag
        keyUp?.flags = cmdFlag
        keyDown?.post(tap: .cgSessionEventTap)
        keyUp?.post(tap: .cgSessionEventTap)
    }

    func clearSystemClipboard() {
        pasteboard.clearContents()
    }

    @objc
    func checkForChangesInPasteboard() {
        autoreleasepool {
            checkForChangesInPasteboardWithinAutoreleasePool()
        }
    }

    private func checkForChangesInPasteboardWithinAutoreleasePool() {
        guard !isSuspended else { return }
        guard pasteboard.changeCount != changeCount else { return }

        changeCount = pasteboard.changeCount

        // 面板自身复制产生的变化：只更新 changeCount，不记录。
        if pasteboard.pasteboardItems?.contains(where: { $0.types.contains(.fromMacPilot) }) == true {
            return
        }

        // 读取类型时 NSPasteboard 会给出所有可用类型，甚至包括
        // NSPasteboardItem 上不存在的类型。
        guard !Self.shouldIgnoreTypes(
            Set(pasteboard.types ?? []),
            supportedTypes: supportedTypes,
            ignoredTypes: ignoredTypes
        ) else { return }

        // 某些应用（BBEdit、Edge）复制时会写入 2 个 item，合并成一个记录。
        let itemID = UUID()
        let contents = Self.captureContents(from: pasteboard.pasteboardItems ?? [], itemID: itemID)

        guard !contents.isEmpty else { return }

        var historyItem = ClipboardItem(id: itemID, contents: contents)
        historyItem.application = frontmostApplicationBundleIdentifier()
        historyItem.title = historyItem.generateTitle()

        onNewCopyHook?(historyItem)
    }

    private func frontmostApplicationBundleIdentifier() -> String? {
        NSWorkspace.shared.frontmostApplication?.bundleIdentifier
    }

    private func clearFormatting(_ contents: [ClipboardContent]) -> [ClipboardContent] {
        let stringContents = contents.filter { NSPasteboard.PasteboardType($0.type) == .string }
        guard !stringContents.isEmpty else { return contents }

        var newContents = stringContents
        let fileURLContents = contents.filter { NSPasteboard.PasteboardType($0.type) == .fileURL }
        if !fileURLContents.isEmpty {
            newContents += fileURLContents
        }
        return newContents
    }
}

// MARK: - 采集决策（纯函数，可单元测试）

extension ClipboardMonitor {
    static let dynamicTypePrefix = "dyn."
    static let microsoftSourcePrefix = "com.microsoft.ole.source."

    static let pollingInterval: TimeInterval = 0.5

    /// 判断粘贴板整体类型集合是否应被忽略：无任何受支持类型，或带忽略标记。
    static func shouldIgnoreTypes(
        _ types: Set<NSPasteboard.PasteboardType>,
        supportedTypes: Set<NSPasteboard.PasteboardType>,
        ignoredTypes: Set<NSPasteboard.PasteboardType>
    ) -> Bool {
        types.isDisjoint(with: supportedTypes) || !types.isDisjoint(with: ignoredTypes)
    }

    /// 把一个粘贴板的全部 items 合并为一条记录的内容列表（按需落盘）。
    /// 类型按名称排序处理，保证结果顺序确定、可测试。
    static func captureContents(
        from items: [NSPasteboardItem],
        itemID: UUID
    ) -> [ClipboardContent] {
        var collected = [ClipboardContent]()
        var index = 0
        for item in items {
            guard let itemContents = contents(for: item, itemID: itemID, index: &index) else { continue }
            collected.append(contentsOf: itemContents)
        }
        return collected
    }

    /// 处理单个 NSPasteboardItem；返回 nil 表示该 item 应被跳过。
    private static func contents(
        for item: NSPasteboardItem,
        itemID: UUID,
        index: inout Int
    ) -> [ClipboardContent]? {
        var types = Set(item.types)
        if types.contains(.string) && isEmptyString(item) && !richText(item) {
            return nil
        }

        types = types
            .filter { !$0.rawValue.starts(with: dynamicTypePrefix) }
            .filter { !$0.rawValue.starts(with: microsoftSourcePrefix) }

        // 避免读取 Microsoft Word 书签与交叉引用链接。
        if types.isSuperset(of: [.microsoftLinkSource, .microsoftObjectLink]) {
            types = types.subtracting([.microsoftLinkSource, .microsoftObjectLink, .pdf])
        }

        var result: [ClipboardContent] = []
        for type in types.sorted(by: { $0.rawValue < $1.rawValue }) {
            let data = item.data(forType: type)
            result.append(makeContent(type: type.rawValue, data: data, itemID: itemID, index: &index))
        }
        return result
    }

    /// 大数据（图片、大段内容）落盘保存，内存里只保留文件引用，减少常驻内存。
    private static func makeContent(
        type: String,
        data: Data?,
        itemID: UUID,
        index: inout Int
    ) -> ClipboardContent {
        defer { index += 1 }
        guard let data, !data.isEmpty else {
            return ClipboardContent(type: type, size: 0)
        }
        let externalize = ClipboardContentStore.shouldExternalizeContent(type: type, dataSize: data.count)
        if externalize, let file = ClipboardContentStore.write(data, itemID: itemID, index: index) {
            return ClipboardContent(type: type, file: file, size: data.count)
        }
        return ClipboardContent(type: type, value: data, size: data.count)
    }

    private static func isEmptyString(_ item: NSPasteboardItem) -> Bool {
        guard let string = item.string(forType: .string) else { return true }
        return string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    private static func richText(_ item: NSPasteboardItem) -> Bool {
        if let rtf = item.data(forType: .rtf),
           let attributedString = NSAttributedString(rtf: rtf, documentAttributes: nil) {
            return !attributedString.string.isEmpty
        }
        if let html = item.data(forType: .html),
           let attributedString = NSAttributedString(html: html, documentAttributes: nil) {
            return !attributedString.string.isEmpty
        }
        return false
    }
}
